In [29]:
import numpy as np

numeri = np.array([[1,3,5,7,9], [0,2,4,6,8]])

numeri.dtype

dtype('int32')

In [30]:
numbers = np.arange(1,6)

np.linspace(1.1, 5.5, 5)

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [31]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [32]:
mask = numbers >= 3
numbers[mask] #Cancella tutto ciò che non è maggiore uguale a 3

array([3, 4, 5])

In [33]:
grades = np.array([[60,80,90],
                  [70,80,50],
                  [70,90,70]])

grades[1]

array([70, 80, 50])

In [42]:
grades[1:3][0:2]

array([[70, 80, 50],
       [70, 90, 70]])